### ISSUE TITLE
Wish: Prevision version of document button

### ISSUE THREAD

**Issue by sergey-safarov** [apache/couchdb-fauxton#913] opened 2017-05-02 14:52 UTC
in couchdb 1.6 exist prevision version of document button.
Could you please add similar to latest fauxton

**Comment by popojargo** [comment] 2018-07-25 13:41
@wohali From what we have already discussed, we don't want to land such feature in Fauxton?

**Comment by wohali** [comment] 2018-07-25 14:03
@popjargo My big concern is that we don't want Fauxton users to mistake this functionality as a fully-fledged version control system - or even a poor one. As you know, document revisions exist only for us to  ensure eventual consistency in CouchDB. They may exist for a short time in the database and are friendly for people to get to, but...

The (good!) default compaction daemon means this feature will more often than not even show the previous revisions, since they won't exist in the system.

OP's request may already be aware of this, but with compaction being a default and old revisions being more aggressively stemmed/removed/possibly automatically in the future, I do think it would be a regression to bring this feature back.

What is Cloudant's take on this? My time there (and with TNH now) suggests that conflicts are poorly understood, and that revision trees are always mistaken as "oh, so I get the whole document history now? Neat!" which is a huge misunderstanding of our little database.

**Comment by popojargo** [comment] 2018-07-25 14:20
I totally agree. As for Cloudant's take, I can't relate since I don't work there and I don't use Cloudant. 😛 

@Antonio-Maranhao @garrensmith I will close this ticket if you don't have any objections?

**Comment by wohali** [comment] 2018-07-25 14:22
Oops, my face is red now. :) Hope I get to see you at ApacheCon when I'm in Montréal in September? (That would be true no matter where you work...)

**Comment by sergey-safarov** [comment] 2018-07-25 15:23
Hello @popojargo , @wohali 
Thank you for this description. I understand now, agree to close ticket.

**Closed** 2018-07-26 20:42 UTC
