### ISSUE TITLE
fauxton starting issue

### ISSUE THREAD

**Issue by MussaratAziz** [apache/couchdb-fauxton#1283] opened 2020-05-22 13:23 UTC
Hi, 
When try to run fauxton getting following error, i think the release is broken
Could not locate C:\Users\Test\AppData\Roaming\npm\node_modules\fauxton\dist\release\index.html
If anybody can point me to right direction it would be great. Thanks

**Comment by popojargo** [comment] 2020-06-09 03:48
Duplicate of #1275

**Closed by popojargo** 2020-06-09 03:48 UTC
