### ISSUE TITLE
ddocs.html HTTP 404

### ISSUE THREAD

**Issue by linquize** [apache/couchdb-fauxton#955] opened 2017-08-13 12:59 UTC
Visit http://localhost:5984/_utils/docs/couchapp/ddocs.html returns HTTP 404

## Expected Behavior
Show the page

## Current Behavior
HTTP 404
Not found.

## Steps to Reproduce (for bugs)
1. Edit View
2. Click the question mark

## Your Environment
* Version used: CouchDB 2.1.0
* Browser Name and version: Firefox 54
* Operating System and version (desktop or mobile): Win 10 x64 version 1703
* Link to your project: N/A

**Comment by wohali** [comment] 2017-08-13 18:17
Our documentation has been reorganised. That page now exists at http://localhost:5984/_utils/docs/ddocs/index.html .

**Comment by wohali** [comment] 2017-08-13 18:18
Sorry, I just realised this is a Fauxton bug with the link going to the wrong place.

**Comment by michellephung** [comment] 2017-08-13 20:40
hey i just merged the offline docs link fix. @linquize can you pull and check again

**Comment by wohali** [comment] 2017-08-13 21:15
@linquize you'll need to build from source, I'm afraid, to test this fix.

**Comment by linquize** [comment] 2017-08-14 01:28
Is it already fixed in master ?  Waiting for next release?

**Comment by michellephung** [comment] 2017-08-14 01:30
it's on master: https://github.com/apache/couchdb-fauxton/commit/dc0cdae33b38a36a5c97e2525b41e8a737df0a96

and will be in the next release. if you want it now, you'll have to build from source

**Comment by wohali** [comment] 2017-08-14 20:02
@michellephung will that fix the link he found though? it's a different source, not the one you fixed.

**Comment by michellephung** [comment] 2017-08-14 20:58
OHHH...i think i thought this was for the offline docs. Sorry! I can check tonight for the ddocs icon

**Comment by michellephung** [comment] 2017-08-14 21:14
looks like the issue is here: https://github.com/apache/couchdb-fauxton/blob/b212dd5b5b8e9aa2f90f125d8c9d14263fa90b99/app/constants.js#L35

and there are some others that will need to be changed as well

**Closed** 2018-01-03 18:26 UTC
